name: Create VPS with Direct SSH (Playit Tunnel & Output Password)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [create-vps]

jobs:
  start-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3

      - name: ✅ Install OpenSSH & Create User
        run: |
          sudo apt update -y
          sudo apt install -y openssh-server
          sudo useradd -m vpsuser
          PASSWORD="$(openssl rand -base64 10)"
          echo "vpsuser:$PASSWORD" | sudo chpasswd
          echo "$PASSWORD" > links/ssh_password.txt
          sudo sed -i 's/Port 22/Port 2222/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: 🚀 Start Playit Tunnel for SSH
        run: |
          wget -q https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64 -O playit
          chmod +x playit
          echo '{"tunnels":[{"proto":"tcp","local_port":2222,"remote_port":0}]}' > playit-config.json
          nohup ./playit --config playit-config.json > playit.log 2>&1 &
          sleep 20
          grep -Eo 'ssh:\/\/[^\"]+' playit.log > playit_ssh.txt || echo "Playit SSH link not found"

      - name: 📤 Output SSH Info & Tunnel
        run: |
          echo "==== SSH LOGIN INFO ===="
          echo "Username: vpsuser" > links/ssh_info.txt
          echo "Password: $(cat links/ssh_password.txt)" >> links/ssh_info.txt
          echo "Local Port: 2222 (tunnel)" >> links/ssh_info.txt
          echo "Playit SSH Tunnel: $(cat playit_ssh.txt)" >> links/ssh_info.txt
          cat links/ssh_info.txt

      - name: ⏳ Keep VPS alive (POSIX-safe loop)
        run: |
          i=1
          while [ $i -le 360 ]; do
            echo "🟢 Running minute $i/360..."
            command sleep 60 || break
            i=$((i+1))
          done
