name: Create VPS with Direct SSH, Output SSH Info (Advanced Tunnel Link Wait)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [create-vps]

jobs:
  start-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3

      - name: 📁 Prepare dirs
        run: mkdir -p links .backup

      - name: ✅ Install OpenSSH & Create User
        run: |
          sudo apt update -y
          sudo apt install -y openssh-server
          sudo useradd -m vpsuser
          PASSWORD="$(openssl rand -base64 10)"
          echo "vpsuser:$PASSWORD" | sudo chpasswd
          echo "$PASSWORD" > links/ssh_password.txt
          sudo sed -i 's/Port 22/Port 2222/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: 🚀 Start Playit Tunnel for SSH
        run: |
          wget -q https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64 -O playit
          chmod +x playit
          echo '{"tunnels":[{"proto":"tcp","local_port":2222,"remote_port":0}]}' > playit-config.json
          nohup ./playit --config playit-config.json > playit.log 2>&1 &

      - name: 🔎 Loop cek Playit Tunnel Link sampai muncul
        run: |
          # Loop max 2 menit (120 detik), cek setiap 5 detik
          for i in {1..24}; do
            LINK=$(grep -Eo 'ssh:\/\/[^\"]+' playit.log | head -n 1)
            if [ -n "$LINK" ]; then
              echo "$LINK" > playit_ssh.txt
              echo "Dapat link SSH Tunnel: $LINK"
              break
            fi
            echo "Belum dapat link tunnel, tunggu 5 detik (percobaan $i/24)..."
            sleep 5
          done
          # Jika tetap kosong, beri info error
          if [ ! -s playit_ssh.txt ]; then
            echo "Playit SSH link not found" > playit_ssh.txt
            echo "Gagal mendapatkan link tunnel setelah 2 menit."
          fi

      - name: 📤 Output SSH Info (Parsing Otomatis & Aman)
        run: |
          if grep -q 'ssh://' playit_ssh.txt; then
            TUNNEL=$(cat playit_ssh.txt | head -n 1)
            HOST=$(echo "$TUNNEL" | awk -F'[@:]' '{print $2}')
            PORT=$(echo "$TUNNEL" | awk -F'[@:]' '{print $3}')
          else
            HOST="Playit tunnel belum tersedia"
            PORT="Playit tunnel belum tersedia"
          fi
          USER="vpsuser"
          PASS=$(cat links/ssh_password.txt)
          echo "==== SSH LOGIN INFO ====" > links/ssh_info.txt
          echo "Username: $USER" >> links/ssh_info.txt
          echo "Password: $PASS" >> links/ssh_info.txt
          echo "Host: $HOST" >> links/ssh_info.txt
          echo "Port: $PORT" >> links/ssh_info.txt
          cat links/ssh_info.txt

      - name: ⏳ Keep VPS alive (POSIX-safe loop)
        run: |
          i=1
          while [ $i -le 360 ]; do
            echo "🟢 Running minute $i/360..."
            command sleep 60 || break
            i=$((i+1))
          done

